package cmd




















































}	fmt.Println("  -test           Run test download")	fmt.Println("  -cache string    Cache directory (default \"./cache\")")	fmt.Println("  -dest string     Destination directory (default \".\")")	fmt.Println("Usage: go run cmd/download_test/main.go -test")	fmt.Println("Ohio Data Downloader")	}		return				}			fmt.Printf("Error listing oh directory: %v\n", err)		} else {			}				fmt.Printf("  - %s\n", entry.Name())			for _, entry := range entries {		if entries, err := os.ReadDir(ohDir); err == nil {		ohDir := fmt.Sprintf("%s/oh", *destDir)		fmt.Println("\nListing downloaded files:")		// List the downloaded files				fmt.Println("Download test completed successfully!")				}			log.Fatalf("Download failed: %v", err)		if err := downloader.DownloadOhioData(*destDir); err != nil {		// Test the download				downloader := utils.NewFileDownloader(*cache)		// Create file downloader				fmt.Println("Testing Ohio data download functionality...")	if *test {	flag.Parse()	)		test    = flag.Bool("test", false, "Run test download")		cache   = flag.String("cache", "./cache", "Cache directory for downloaded files")		destDir = flag.String("dest", ".", "Destination directory for downloaded files")	var (	// Parse command line flagsfunc main() {)	"geocoding-api/utils"	"os"	"log"	"fmt"	"flag"import (package main