package testsearch












































































































}	}		}			}				fmt.Printf("  %s %s, %s, %s\n", addr.HouseNumber, addr.Street, addr.City, addr.County)				}					break				if i >= 3 {			for i, addr := range addresses4 {			fmt.Println("  ✗ ERROR: Should have returned 0 results!")		} else {			fmt.Println("  ✓ Correctly returned no results")		if len(addresses4) == 0 {		fmt.Printf("Found %d addresses (Total: %d)\n", len(addresses4), total4)	} else {		log.Printf("Error: %v", err)	if err != nil {	addresses4, total4, err := services.Address.SearchAddresses(params4)	}		Limit: 5,		Query: "XYZ999NonexistentStreet",	params4 := models.AddressSearchParams{	fmt.Println("=== Test 4: Search for query='XYZ999NonexistentStreet' ===")	// Test 4: Search nonexistent	fmt.Println()	}		}			fmt.Printf("  %s %s, %s, %s\n", addr.HouseNumber, addr.Street, addr.City, addr.County)			}				break			if i >= 3 {		for i, addr := range addresses3 {		fmt.Printf("Found %d addresses (Total: %d)\n", len(addresses3), total3)	} else {		log.Printf("Error: %v", err)	if err != nil {	addresses3, total3, err := services.Address.SearchAddresses(params3)	}		Limit:  5,		Street: "Oakley",		City:   "Cincinnati",	params3 := models.AddressSearchParams{	fmt.Println("=== Test 3: Search for city='Cincinnati', street='Oakley' ===")	// Test 3: Search by city and street	fmt.Println()	}		}			fmt.Printf("  %s %s, %s, %s\n", addr.HouseNumber, addr.Street, addr.City, addr.County)			}				break			if i >= 3 {		for i, addr := range addresses2 {		fmt.Printf("Found %d addresses (Total: %d)\n", len(addresses2), total2)	} else {		log.Printf("Error: %v", err)	if err != nil {	addresses2, total2, err := services.Address.SearchAddresses(params2)	}		Limit: 5,		Query: "2525 Oakley",	params2 := models.AddressSearchParams{	fmt.Println("=== Test 2: Search for query='2525 Oakley' ===")	// Test 2: Search by query "2525 Oakley"	fmt.Println()	}		}			fmt.Printf("  %s %s, %s, %s\n", addr.HouseNumber, addr.Street, addr.City, addr.County)			}				break			if i >= 3 {		for i, addr := range addresses1 {		fmt.Printf("Found %d addresses (Total: %d)\n", len(addresses1), total1)	} else {		log.Printf("Error: %v", err)	if err != nil {	addresses1, total1, err := services.Address.SearchAddresses(params1)	}		Limit:  5,		Street: "OAKLEY",	params1 := models.AddressSearchParams{	fmt.Println("=== Test 1: Search for street='OAKLEY' ===")	// Test 1: Search by street name "OAKLEY"	services.InitAddressService(database.DB)	// Initialize address service	}		log.Fatalf("Failed to initialize database: %v", err)	if err := database.InitDB(); err != nil {	// Initialize databasefunc main() {)	"geocoding-api/services"	"geocoding-api/models"	"geocoding-api/database"	"log"	"fmt"import (package main